server:
  port: 8080
spring:
  application:
    name: wau-auth
  profiles:
    active: local
  main:
    h2:
      console:
        enabled: true
        path: /h2-console
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:~/account
      username: sa
      password:


